time <-
  c(
    "reproductive success",
    "fledging success",
    "reproductive performance",
    "pairing success",
    "parasitism rates",
    "provisioning rates",
    "reduced fecundity",
    "singing males",
    "territorial males",
    "territory density",
    "territory occupancy",
    "ground nests",
    "young fledged",
    "breeding",
    "reproduction",
    "nesting",
    "fledgling"
  )
outcome <-
  c(
    "imperfect detection",
    "population density",
    "population persistence",
    "detection probability",
    "local extinction",
    "total number",
    "population status",
    "remaining populations",
    "adult mortality",
    "area-sensitive species",
    "population dynamics",
    "population growth",
    "population estimate",
    "breeding population",
    "total population",
    "demographic parameters",
    "density increased",
    "population sizes",
    "wildlife population",
    "higher density",
    "highest density",
    "effective population",
    "population trend",
    "lower density",
    "occupied patch",
    "small population",
    "population sinks",
    "population viability",
    "relative density",
    "population decline",
    "local population",
    "population change",
    "species increased",
    "species occurrence",
    "stable population",
    "species present",
    "population model",
    "survival rates",
    "abundance",
    "area sensitive",
    "area sensitivity",
    "occupancy",
    "point count",
    "survivorship",
    "species composition"
  )

population <-
  c(
    "forest interior species",
    "avian responses",
    "avian species",
    "dendroica cerulea",
    "dumetella carolinensis",
    "hylocichla mustelina",
    "oporornis formosus",
    "piranga olivacea",
    "seiurus aurocapilla",
    "seiurus aurocapillus",
    "sensitive species",
    "setophaga chrysoparia",
    "singing males",
    "wilsonia citrina",
    "young fledged",
    "passerine",
    "passeriformes",
    "bird",
    "warbler",
    "thrush",
    "vireo",
    "nuthatch",
    "kinglet",
    "flycatcher",
    "tanager",
    "avian community",
    "chickadee",
    'wren',
    "veery"
  )

intervention <-
  c(
    "landscape management",
    "vegetation structure",
    "island biogeography",
    "agricultural landscape",
    "continuous forest",
    "landscape metrics",
    "larger patches",
    "smaller patches",
    "forest patch",
    "habitat amount",
    "landscape composition",
    "total forest",
    "forest cover",
    "forest structure",
    "forested areas",
    "forest opening",
    "large forest",
    "habitat alteration",
    "habitat change",
    "habitat configuration",
    "habitat degradation",
    "habitat disturbance",
    "habitat heterogeneity",
    "habitat patch",
    "habitat quality",
    "habitat requirement",
    "heterogeneous landscape",
    "forest edges",
    "landscape attributes",
    "landscape characteristics",
    "landscape context",
    "landscape ecology",
    "landscape effects",
    "landscape features",
    "landscape level",
    "landscape pattern",
    "landscape scale",
    "landscape structure",
    "landscape variable",
    "large areas",
    "large patches",
    "large tracts",
    "natural disturbance",
    "occupied patch",
    "intact forest",
    "patch isolation",
    "forest stand",
    "forest tract",
    "patch occupancy",
    "patch scale",
    "quality habitat",
    "sensitive species",
    "small patch",
    "small woodlots",
    "spatial configuration",
    "surrounding landscape",
    "urbanizing landscape",
    "urban landscape",
    "woodland patch",
    "fragment",
    "remnant",
    "patch size",
    "area sensitive",
    "forest corridor",
    "forest area",
    "woodland area",
    "woodlot area",
    "grove size",
    "habitat island",
    "habitat area",
    "area requirement",
    "forest island",
    "forest size", "small forest")

space <- c("canopy cover", "forest", "woodland", "woodlot", "broadleaf", "coniferous", 'deciduous')

